with HAL; use HAL;

PROCEDURE PGM2 IS

  POINT1   : INTEGER := 10;
  POINT2   : INTEGER := -10;
  POINT3   : INTEGER := -20;
  POINT4   : INTEGER := 0;
  POINT5   : INTEGER := 100;
  FINISHED : INTEGER;

  TASK CALCULATOR IS
     ENTRY GET_LENGTH(POINTA, POINTB : INTEGER;
                      LENGTH : OUT INTEGER);
     ENTRY GET_MIDPOINT(POINTA, POINTB : INTEGER;
                        POINTC : OUT INTEGER);
     ENTRY DONE;
     ENTRY ACK;
  END CALCULATOR;

  TASK GEOM_A;

  TASK GEOM_B;

  TASK GEOM_C;

  TASK BODY GEOM_A IS
     LENGTH   : INTEGER;
     MIDPOINT : INTEGER;
  BEGIN
     CALCULATOR.GET_LENGTH(POINT2,POINT1,LENGTH);
     CALCULATOR.GET_MIDPOINT(POINT1,POINT5,MIDPOINT);
     CALCULATOR.ACK;
  END GEOM_A;

  TASK BODY GEOM_B IS
     LENGTH   : INTEGER;
     MIDPOINT : INTEGER;
  BEGIN
     CALCULATOR.GET_MIDPOINT(POINT2,POINT3,MIDPOINT);
     CALCULATOR.GET_MIDPOINT(POINT3,POINT5,MIDPOINT);
     CALCULATOR.ACK;
  END GEOM_B;

  TASK BODY GEOM_C IS
     LENGTH   : INTEGER;
     MIDPOINT : INTEGER;
  BEGIN
     CALCULATOR.GET_MIDPOINT(POINT1,POINT4,MIDPOINT);
     CALCULATOR.GET_LENGTH(POINT5,POINT2,LENGTH);
     CALCULATOR.GET_MIDPOINT(POINT4,POINT1,MIDPOINT);
     CALCULATOR.ACK;
  END GEOM_C;

  TASK BODY CALCULATOR IS
  BEGIN
     FINISHED := 0;
     LOOP
        SELECT
           ACCEPT GET_LENGTH(POINTA, POINTB : INTEGER;
                             LENGTH : OUT INTEGER) DO
              LENGTH := POINTB - POINTA;
           END GET_LENGTH;
        OR
           ACCEPT GET_MIDPOINT(POINTA, POINTB : INTEGER;
                               POINTC : OUT INTEGER) DO
              POINTC := (POINTA + POINTB) / 2;
           END GET_MIDPOINT;
        OR
           ACCEPT ACK DO
              FINISHED := FINISHED + 1;
           END ACK;
        OR
           WHEN FINISHED = 3 =>
              ACCEPT DONE DO
                 NULL;
              END DONE;
        OR
           TERMINATE;
        END SELECT;
     END LOOP;
  END CALCULATOR;

BEGIN
   CALCULATOR.DONE;
   PUT("POINT1 = "); PUT_LINE(POINT1);
   PUT("POINT2 = "); PUT_LINE(POINT2);
   PUT("POINT3 = "); PUT_LINE(POINT3);
   PUT("POINT4 = "); PUT_LINE(POINT4);
   PUT("POINT5 = "); PUT_LINE(POINT5);
END PGM2;
